### ISSUE TITLE
socket connect() failed

### ISSUE THREAD

**Issue by jie-lin** [libvmi/libvmi#333]
Using volatility combined with pyvmi to introspect qemu-kvm failed most of time. The connect() in libvmi/driver/kvm/kvm.c may fail with return value -1 and errno value 2, which means "No such file or directory". If sleep(1); is added before connect(), introspection will succeed. So the connect() on the client side might execute before accept() on the server side.

**Comment by Wenzel** [comment]
I've just got the same issue here.

If someone wants to fix it properly, we should not add a `sleep` before the call to `connect` in `memory-access.c`, but instead wait for the socket to be created by QEMU in the kvm driver.

**Comment by Wenzel** [comment]
@jie-lin This issue should be fixed with the latest update of the memory access patch for QEMU.
-> see this commit 4674a9a2a2500e2feaa4e06881ad0bb10a10ad73

@tklengyel maybe we can close this issue now ?

**Comment by aghamir** [comment]
I used qemu with this patch but it doesn't fix.
the output of executing process-list is here:
```
--found KVM
LibVMI Version 0.11.0
LibVMI Driver Mode 1
--completed driver init.
--got id from name (ubuntu16.04 --> 3)
**set image_type = ubuntu16.04
--libvirt version 1003001
--qmp: virsh -c qemu:///system qemu-monitor-command ubuntu16.04 '{"execute": "pmemaccess", "arguments": {"path": "/tmp/vmij0gjAi"}}'
--kvm: using custom patch for fast memory access
--connect() failed to /tmp/vmij0gjAi, No such file or directory
Failed to init LibVMI library.
```

**Comment by aladinggit** [comment]
@aghamir @Wenzel I just got the same issue using patched Qemu(4.1.0) and Libvmi(0.13.0). Have anyone of you guys found the solution so you can shed me some light?
:~/libvmi/build/examples$ sudo ./vmi-process-list -n test_virsh
--found KVM
Running Bareflank CPUID signature: 3000 4700 100 0
LibVMI Version 0.13.0
LibVMI Driver Mode 1
--completed driver init.
--got id from name (test_virsh --> 10)
**set image_type = test_virsh
--libvirt version 4000000
--qmp: {"execute": "query-version"}
--Checking QEMU version string...
--SUCCESS
--qmp: {"execute": "pmemaccess", "arguments": {"path": "/tmp/vmirqadw5"}}
--kvm: using custom patch for fast memory access
--connect() failed to /tmp/vmirqadw5, No such file or directory
Failed to init LibVMI library.
